### ISSUE TITLE
Description and subject are the same 

### ISSUE THREAD

**Issue by sthilairek** [espace/redmine_import_from_csv#7]
I have a question really how would one modify the plugin so that the subject and description are not the same. everytime when I do an import it has the same information for the subject and description. it is very annoying please tell me how to fix.

**Comment by sthilairek** [comment]
if you look at the file import_from_csv_controller.rb in this location: 

/opt/redmine-2.4.2-0/apps/redmine/htdocs/plugins/redmine_import_from_csv/app/controllers
and look for issue.description you will see that is says 
 issue.description=(subject.nil? ? "" : subject)+(description.nil? ? "" : "\n\nh3. Notes\n\n"+description)

what I did was delete all of that and have it say 
issue.description=(description)

and it works now

**Comment by basayel** [comment]
Thanks for sharing this

I had applied this modification according to this commit https://github.com/espace/redmine_import_from_csv/commit/06ae3cf71625ace5e29d62d03781e909bd6b222a
